
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
  labels:
    app: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: simplemicroserviceapp 
    spec:
      containers:
      - name: simplemicroserviceapp
        image: #path to your docker image
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: simplemicroserviceapp-app-service
spec:
  selector:
    app: simplemicroserviceapp 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 8080
    nodePort: 31110